# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlpDMaKTFMSAj_V2BruS3kC5lPKMxCGn
"""

# agents/__init__.py
"""
Agent modules for the multi-agent AI assistant system.

Available agents:
- WeatherAgent: Fetches weather data
- EventAgent: Queries event database
- RecommendationAgent: Generates personalized recommendations
- RAGAgent: Document-based question answering
- ImageAgent: Text-to-image generation
"""