# -*- coding: utf-8 -*-
"""event_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD5X6r3A06XKwMTKGkSmNYluQTuRzKBA
"""

import sqlite3
from typing import List, Dict, Optional
from datetime import datetime


class EventAgent:
    """Queries events from SQLite database."""

    def __init__(self, db_path: str = "events.db"):
        self.db_path = db_path

    def get_events(
        self,
        date: str,
        event_type: Optional[str] = None,
        min_price: Optional[float] = None,
        max_price: Optional[float] = None,
        min_capacity: Optional[int] = None
    ) -> List[Dict]:
        """
        Query events from database with filters.

        Args:
            date: Event date in YYYY-MM-DD format
            event_type: Filter by event type (optional)
            min_price: Minimum price filter (optional)
            max_price: Maximum price filter (optional)
            min_capacity: Minimum capacity filter (optional)

        Returns:
            List of event dictionaries
        """
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row  # Return rows as dictionaries
        cursor = conn.cursor()

        try:
            # Build dynamic query
            query = "SELECT * FROM events WHERE date = :date"
            params = {"date": date}

            if event_type:
                query += " AND type = :event_type"
                params["event_type"] = event_type
            if min_price is not None:
                query += " AND price >= :min_price"
                params["min_price"] = min_price
            if max_price is not None:
                query += " AND price <= :max_price"
                params["max_price"] = max_price
            if min_capacity is not None:
                query += " AND capacity >= :min_capacity"
                params["min_capacity"] = min_capacity

            cursor.execute(query, params)
            rows = cursor.fetchall()

            # Convert to list of dictionaries
            events = [dict(row) for row in rows]
            return events

        except sqlite3.Error as e:
            raise Exception(f"Database error: {str(e)}")
        finally:
            conn.close()