# -*- coding: utf-8 -*-
"""image_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13by6hahCQjB78lVCbxpRdRivnnfksxYn
"""

# ============================================================================
# FILE: agents/image_agent.py
# ============================================================================
"""
Image Agent - Handles image generation.
"""
import openai
from typing import Optional


class ImageAgent:
    """Generates images using DALL-E."""

    def __init__(
        self,
        api_key: str,
        model: str = "dall-e-3",
        size: str = "1024x1024"
    ):
        self.client = openai.OpenAI(api_key=api_key)
        self.model = model
        self.size = size

    def generate_image(self, prompt: str, quality: str = "standard") -> str:
        """
        Generate an image from text prompt.

        Args:
            prompt: Text description of desired image
            quality: "standard" or "hd"

        Returns:
            URL of generated image
        """
        try:
            response = self.client.images.generate(
                model=self.model,
                prompt=prompt,
                size=self.size,
                quality=quality,
                n=1
            )
            return response.data[0].url
        except Exception as e:
            raise Exception(f"Image generation error: {str(e)}")