# -*- coding: utf-8 -*-
"""rag_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLdo8OZFnS51uka7mrHCGZ8VQafhsbPG
"""

# ============================================================================
# FILE: agents/rag_agent.py
# ============================================================================
"""
RAG Agent - Document-based Question Answering.
"""
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from typing import Optional


class RAGAgent:
    """Handles document-based question answering."""

    def __init__(
        self,
        api_key: str,
        pdf_path: str,
        model: str = "gpt-5-mini",
        llm_provider: str = "openai",
        ollama_base_url: str = "",
        qwen_api_key: str = "",
        qwen_base_url: str = "",
    ):
        self.api_key = api_key
        self.model = model
        self.llm_provider = (llm_provider or "openai").lower()
        self.ollama_base_url = ollama_base_url.rstrip("/")
        self.qwen_api_key = qwen_api_key
        self.qwen_base_url = qwen_base_url.rstrip("/")
        self.vector_store = None
        self.chain = None

        # Load and process document
        self._load_document(pdf_path)

    def _load_document(self, pdf_path: str):
        """Load PDF and create vector store."""
        # Load PDF
        loader = PyMuPDFLoader(pdf_path)
        documents = loader.load()

        # Split into chunks
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200
        )
        chunks = text_splitter.split_documents(documents)

        # Create embeddings and vector store
        embeddings = OpenAIEmbeddings(openai_api_key=self.api_key)
        self.vector_store = FAISS.from_documents(chunks, embeddings)

        # Create retrieval chain
        self._create_chain()

    def _create_chain(self):
        """Create the RAG chain."""
        llm = None
        if self.llm_provider == "ollama":
            try:
                from langchain_community.chat_models import ChatOllama
                llm = ChatOllama(
                    model=self.model,
                    temperature=0,
                    base_url=self.ollama_base_url or None
                )
            except Exception as e:
                print(f"[RAG] Ollama LLM init failed, falling back to OpenAI: {e}")
        elif self.llm_provider == "qwen":
            try:
                llm = ChatOpenAI(
                    model=self.model,
                    temperature=0,
                    openai_api_key=self.qwen_api_key,
                    base_url=self.qwen_base_url
                )
            except Exception as e:
                print(f"[RAG] Qwen LLM init failed, falling back to OpenAI: {e}")

        if llm is None:
            llm = ChatOpenAI(
                model=self.model,
                temperature=0,
                openai_api_key=self.api_key
            )

        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are Amanda, a professional tourism advisor and customer service assistant for travelers.
Use a friendly, less formal, customer-first tone with light emojis where appropriate.
Use the provided context to answer accurately, clearly, and helpfully for tourists.
If the answer is not in context, say so directly and avoid making up details."""),
            ("user", "Context: {context}\n\nQuestion: {question}")
        ])

        retriever = self.vector_store.as_retriever(search_kwargs={"k": 4})

        self.chain = (
            {"context": retriever, "question": RunnablePassthrough()}
            | prompt
            | llm
            | StrOutputParser()
        )

    def query(self, question: str) -> str:
        """Answer a question using RAG."""
        try:
            return self.chain.invoke(question)
        except Exception as e:
            raise Exception(f"RAG query error: {str(e)}")
