# -*- coding: utf-8 -*-
"""recommendation_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRNCQFQ2pW_zQiUp8HJsZD2QFmZO1ZcL
"""

# ============================================================================
# FILE: agents/recommendation_agent.py
# ============================================================================
"""
Recommendation Agent - Generates personalized recommendations using LLM.
"""
import openai
from typing import Dict, List


class RecommendationAgent:
    """Generates event recommendations based on weather and events."""

    def __init__(self, api_key: str, model: str = "gpt-4"):
        self.client = openai.OpenAI(api_key=api_key)
        self.model = model

    def generate_recommendation(
        self,
        weather_data: Dict,
        events: List[Dict]
    ) -> str:
        """
        Generate personalized recommendations.

        Args:
            weather_data: Weather information dictionary
            events: List of available events

        Returns:
            Recommendation text
        """
        # Build context
        context = self._build_context(weather_data, events)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self._get_system_prompt()},
                    {"role": "user", "content": context}
                ],
                temperature=0.7
            )
            return response.choices[0].message.content
        except Exception as e:
            raise Exception(f"Recommendation generation error: {str(e)}")

    def _build_context(self, weather_data: Dict, events: List[Dict]) -> str:
        """Build context string for LLM."""
        context = f"""Weather Conditions:
- Condition: {weather_data.get('condition', 'Unknown')}
- Temperature: {weather_data.get('temperature_c', 'N/A')}°C
- UV Index: {weather_data.get('uv_index', 'N/A')}
- Chance of Rain: {weather_data.get('rain_chance', 'N/A')}%
- Humidity: {weather_data.get('humidity', 'N/A')}%

Available Events:
"""
        for event in events:
            context += f"""
- {event.get('name', 'N/A')} ({event.get('type', 'N/A')})
  Time: {event.get('time', 'N/A')}
  Price: ${event.get('price', 0):.2f}
  Capacity: {event.get('capacity', 'N/A')}
  Description: {event.get('description', 'N/A')}
"""
        return context

    def _get_system_prompt(self) -> str:
        """Return system prompt for recommendation agent."""
        return """You are an intelligent event recommendation assistant.

Your task:
1. Analyze weather conditions and suggest appropriate events
2. For bad weather (rain, extreme heat), prioritize indoor events
3. For good weather, suggest outdoor activities
4. Group recommendations by time of day (Morning, Afternoon, Evening)
5. Consider price and capacity when recommending
6. Provide transport suggestions based on weather
7. Be concise but informative

Format your response with clear sections and bullet points."""