# -*- coding: utf-8 -*-
"""weather_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN6u2agm1FGGtnGmDjYgmPixS7LO4GWy
"""

# ============================================================================
# FILE: agents/weather_agent.py
# ============================================================================
"""
Weather Agent - Handles weather data retrieval.
"""
import requests
from typing import Dict, Optional


class WeatherAgent:
    """Fetches weather data from WeatherAPI."""

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "http://api.weatherapi.com/v1/forecast.json"

    def get_weather(self, location: str, date: str = None) -> Dict:
        """
        Get weather data for a location.

        Args:
            location: City name or coordinates
            date: Date in YYYY-MM-DD format (optional)

        Returns:
            Dictionary containing weather information
        """
        params = {
            "key": self.api_key,
            "q": location,
            "days": 1,
            "aqi": "no"
        }

        try:
            response = requests.get(self.base_url, params=params, timeout=10)
            response.raise_for_status()
            data = response.json()

            # Extract relevant information
            current = data['current']
            forecast_day = data['forecast']['forecastday'][0]['day']

            return {
                'location': data['location']['name'],
                'condition': current['condition']['text'],
                'temperature_c': current['temp_c'],
                'uv_index': forecast_day['uv'],
                'rain_chance': forecast_day['daily_chance_of_rain'],
                'humidity': current['humidity'],
                'wind_speed_kph': current['wind_kph']
            }
        except requests.exceptions.RequestException as e:
            raise Exception(f"Weather API error: {str(e)}")